import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '@/lib/customSupabaseClient';
import { Star, Loader2, AlertTriangle, CheckCircle2, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

// Public, no-login page opened from a shareable link (e.g.
// /feedback/<token>) generated by clinic staff for one patient. Captures a
// star rating + optional comment via submit_patient_feedback(); a 4-5 star
// rating gets an onward link to the clinic's Google review page (only when
// the clinic has a google_place_id configured) so the same visit can also
// become a public Google review, while low ratings stay internal.
const PatientFeedbackPage = () => {
  const { token } = useParams();
  const [status, setStatus] = useState('loading'); // loading | form | already | invalid | submitted
  const [clinicName, setClinicName] = useState('');
  const [rating, setRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [comment, setComment] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [googleReviewUrl, setGoogleReviewUrl] = useState(null);

  useEffect(() => {
    let cancelled = false;

    const fetchLink = async () => {
      const { data, error } = await supabase
        .rpc('get_feedback_link_info', { p_token: token })
        .maybeSingle();

      if (cancelled) return;

      if (error || !data) {
        setStatus('invalid');
        return;
      }

      setClinicName(data.clinic_name || '');
      setStatus(data.already_responded ? 'already' : 'form');
    };

    if (token) fetchLink();
    else setStatus('invalid');

    return () => { cancelled = true; };
  }, [token]);

  const handleSubmit = async () => {
    if (rating < 1) return;
    setSubmitting(true);
    const { data, error } = await supabase
      .rpc('submit_patient_feedback', { p_token: token, p_rating: rating, p_comment: comment })
      .maybeSingle();
    setSubmitting(false);

    if (error || !data?.success) {
      setStatus('already');
      return;
    }

    setGoogleReviewUrl(data.google_review_url || null);
    setStatus('submitted');
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 p-4">
      <div className="w-full max-w-md bg-white rounded-2xl shadow-2xl overflow-hidden">
        <div className="bg-gradient-to-br from-indigo-600 to-indigo-800 px-6 py-8 text-center text-white">
          <div className="mx-auto w-14 h-14 rounded-full bg-white/15 flex items-center justify-center mb-3">
            <Star className="w-7 h-7" />
          </div>
          <h1 className="text-lg font-bold">Bagaimana Pengalaman Anda?</h1>
          {clinicName && <p className="text-indigo-200 text-sm mt-0.5">{clinicName}</p>}
        </div>

        <div className="p-6">
          {status === 'loading' && (
            <div className="py-6 flex flex-col items-center gap-3 text-slate-500">
              <Loader2 className="w-6 h-6 animate-spin" />
              <p className="text-sm">Menyiapkan form feedback...</p>
            </div>
          )}

          {status === 'invalid' && (
            <div className="py-6 flex flex-col items-center gap-3 text-red-500 text-center">
              <AlertTriangle className="w-8 h-8" />
              <p className="text-sm text-slate-600">Link feedback tidak ditemukan atau sudah tidak berlaku.</p>
            </div>
          )}

          {status === 'already' && (
            <div className="py-6 flex flex-col items-center gap-3 text-center">
              <CheckCircle2 className="w-8 h-8 text-green-500" />
              <p className="text-sm text-slate-600">Terima kasih, feedback untuk link ini sudah pernah dikirim sebelumnya.</p>
            </div>
          )}

          {status === 'form' && (
            <div className="space-y-5">
              <div className="flex justify-center gap-2">
                {Array.from({ length: 5 }).map((_, i) => {
                  const value = i + 1;
                  const filled = value <= (hoverRating || rating);
                  return (
                    <button
                      key={value}
                      type="button"
                      onClick={() => setRating(value)}
                      onMouseEnter={() => setHoverRating(value)}
                      onMouseLeave={() => setHoverRating(0)}
                      className="p-1"
                      aria-label={`${value} bintang`}
                    >
                      <Star className={`w-9 h-9 transition-colors ${filled ? 'fill-amber-400 text-amber-400' : 'text-slate-200'}`} />
                    </button>
                  );
                })}
              </div>
              <Textarea
                placeholder="Ceritakan pengalaman Anda (opsional)"
                value={comment}
                onChange={(e) => setComment(e.target.value)}
                rows={4}
              />
              <Button
                onClick={handleSubmit}
                disabled={rating < 1 || submitting}
                className="w-full bg-indigo-600 hover:bg-indigo-700"
              >
                {submitting && <Loader2 className="w-4 h-4 animate-spin mr-2" />} Kirim Feedback
              </Button>
            </div>
          )}

          {status === 'submitted' && (
            <div className="py-4 flex flex-col items-center gap-4 text-center">
              <CheckCircle2 className="w-10 h-10 text-green-500" />
              <p className="text-sm text-slate-600">Terima kasih atas feedback Anda!</p>
              {googleReviewUrl && (
                <>
                  <p className="text-sm text-slate-500">
                    Senang mendengarnya! Mau bantu klinik dengan membagikan ulasan singkat di Google?
                  </p>
                  <a
                    href={googleReviewUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full"
                    onClick={() => supabase.rpc('mark_feedback_google_review_clicked', { p_token: token })}
                  >
                    <Button className="w-full bg-blue-600 hover:bg-blue-700">
                      <ExternalLink className="w-4 h-4 mr-2" /> Tulis Ulasan di Google
                    </Button>
                  </a>
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PatientFeedbackPage;
