-- Template Edukasi (Saran dan Rekomendasi) gaya resume, dari file Excel "Edukasi Saran Rekomendasi Kaffah 329 Diagnosa".
-- Poin-poin anjuran per diagnosa disimpan di kolom advice; bila terisi, form SOAP memakainya menggantikan susunan lama.
alter table public.diagnosis_education add column if not exists advice text;
with s(id,txt) as (values
(0,$e$- Lakukan latihan batuk efektif dan pernapasan dalam secara rutin untuk membantu mengeluarkan dahak, serta cukupi kebutuhan minum agar dahak lebih encer.$e$),
(1,$e$- Tingkatkan aktivitas secara bertahap dan beristirahat cukup selama masa pemulihan.$e$),
(2,$e$- Hindari paparan asap rokok, debu, dan polusi.$e$),
(3,$e$- Informasikan kepada dokter apabila sesak terasa bertambah berat, atau disertai demam tinggi maupun nyeri dada.$e$),
(4,$e$- Kenali dan hindari pemicu sesak seperti debu, asap, atau udara dingin, dan bawa obat sesuai anjuran dokter saat beraktivitas.$e$),
(5,$e$- Lakukan pernapasan perlahan dengan teknik pursed-lip breathing saat napas terasa berat.$e$),
(6,$e$- Cukupi kebutuhan minum agar dahak lebih mudah dikeluarkan.$e$),
(7,$e$- Biasakan melakukan latihan pernapasan diafragma dan pursed-lip breathing setiap hari, terutama saat napas terasa berat atau sebelum beraktivitas.$e$),
(8,$e$- Atur aktivitas dengan jeda istirahat yang cukup dan tingkatkan secara bertahap sesuai kemampuan napas.$e$),
(9,$e$- Tingkatkan aktivitas secara bertahap dan sisipkan waktu istirahat, karena tenaga biasanya pulih sedikit demi sedikit.$e$),
(10,$e$- Hindari memaksakan olahraga berat pada hari ketika tubuh terasa sangat lelah.$e$),
(11,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan diafragma serta pursed-lip breathing.$e$),
(12,$e$- Lakukan latihan pernapasan dan atur tempo aktivitas agar napas tidak terlalu cepat, serta berhenti sejenak untuk beristirahat bila terasa sesak.$e$),
(13,$e$- Tingkatkan aktivitas secara bertahap sesuai kemampuan.$e$),
(14,$e$- Lakukan latihan pernapasan dan latihan duduk atau berdiri secara bertahap bersama terapis agar tenaga dan napas pulih perlahan.$e$),
(15,$e$- Mulailah dengan aktivitas yang nyaman lalu tambahkan sedikit demi sedikit setiap minggu, dengan jeda istirahat yang teratur.$e$),
(16,$e$- Luangkan waktu untuk latihan pernapasan atau relaksasi setiap hari.$e$),
(17,$e$- Jaga pola tidur yang teratur.$e$),
(18,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya relaksasi progresif / body scan serta pernapasan diafragma.$e$),
(19,$e$- Informasikan kepada terapis apabila keluhan terasa bertambah atau muncul keluhan baru, agar program dapat disesuaikan.$e$),
(20,$e$- Lakukan latihan keseimbangan di dekat pegangan yang kokoh dan tingkatkan tantangannya secara bertahap sesuai arahan terapis.$e$),
(21,$e$- Pastikan rumah aman: lantai tidak licin, penerangan cukup, dan tersedia pegangan di kamar mandi.$e$),
(22,$e$- Gunakan alas kaki yang pas dan alat bantu jalan sesuai anjuran, serta bangun dari duduk atau berbaring secara perlahan.$e$),
(23,$e$- Atur aktivitas dengan jeda istirahat yang teratur dan tingkatkan secara bertahap, agar tenaga tidak terkuras berlebihan dalam satu waktu.$e$),
(24,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya mobilitas di tempat tidur dan transfer serta pernapasan diafragma.$e$),
(25,$e$- Pilih aktivitas yang menopang berat badan seperti berjalan, dan hindari membungkuk atau memutar badan secara berlebihan saat mengangkat beban.$e$),
(26,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan ekspansi iga lateral serta aktivasi transversus abdominis.$e$),
(27,$e$- Tetap bergerak ringan setiap hari, dan hindari mendiamkan sendi terlalu lama agar tidak terasa kaku.$e$),
(28,$e$- Naikkan aktivitas secara bertahap sesuai kemampuan.$e$),
(29,$e$- Catat perkembangan keluhan agar dapat dibahas pada kunjungan berikutnya.$e$),
(30,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan umum serta bersepeda statis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(31,$e$- Kompres hangat pada area otot yang tegang selama 10–15 menit apabila terasa kaku, dan kompres dingin apabila nyeri meningkat setelah aktivitas.$e$),
(32,$e$- Bergerak sedikit demi sedikit beberapa kali dalam sehari, misalnya berpindah duduk dan berdiri, agar tubuh tetap terbiasa bergerak.$e$),
(33,$e$- Lanjutkan aktivitas sehari-hari sesuai kemampuan dan naikkan secara bertahap.$e$),
(34,$e$- Lakukan peregangan ringan dan beristirahat dengan cukup.$e$),
(35,$e$- Sampaikan perkembangan keluhan pada kunjungan berikutnya.$e$),
(36,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan umum serta pernapasan diafragma.$e$),
(37,$e$- Perhatikan hubungan nyeri dengan gerakan, makan, dan buang air besar, lalu sampaikan kepada terapis atau dokter.$e$),
(38,$e$- Pastikan penyebab dari organ dalam telah diperiksa oleh dokter.$e$),
(39,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan diafragma serta relaksasi progresif / body scan.$e$),
(40,$e$- Informasikan kepada dokter apabila terdapat demam, muntah terus-menerus, atau buang air besar berdarah.$e$),
(41,$e$- Tingkatkan jarak atau intensitas lari secara bertahap, dan lakukan peregangan serta penguatan betis secara rutin.$e$),
(42,$e$- Ikuti anjuran dokter mengenai penggunaan alat bantu, batas gerak, dan beban pada area yang dioperasi atau cedera.$e$),
(43,$e$- Jaga luka tetap bersih dan kering apabila terdapat luka operasi.$e$),
(44,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ankle pump dan alfabet serta ROM aktif pergelangan kaki.$e$),
(45,$e$- Informasikan kepada dokter atau terapis apabila terdapat demam, luka yang kemerahan atau mengeluarkan cairan, maupun bengkak dan nyeri pada betis.$e$),
(46,$e$- Periksa kulit pada ujung anggota gerak setiap hari dan jaga kebersihannya, serta luruskan posisi sendi saat beristirahat.$e$),
(47,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya positioning stump dan peregangan anti-kontraktur serta penguatan otot residual dan sendi proksimal.$e$),
(48,$e$- Hindari membawa beban berat dan menyilangkan lengan di depan dada secara paksa hingga nyeri berkurang.$e$),
(49,$e$- Kurangi sementara aktivitas yang memicu nyeri pada area cedera, lalu mulai bergerak kembali secara bertahap sesuai arahan terapis.$e$),
(50,$e$- Hindari pijatan yang terlalu keras pada area yang baru cedera.$e$),
(51,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pendulum serta scapular setting, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(52,$e$- Kompres dingin pada area yang nyeri atau bengkak selama 10–15 menit pada beberapa hari pertama, terutama setelah beraktivitas.$e$),
(53,$e$- Hindari gerakan menendang, berlari cepat, atau berubah arah mendadak sampai kekuatan otot kembali baik, lalu tingkatkan secara bertahap.$e$),
(54,$e$- Kembali ke olahraga atau aktivitas berat secara bertahap setelah nyeri berkurang dan kekuatan membaik.$e$),
(55,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik adduksi serta peregangan adduktor, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(56,$e$- Gunakan penyangga pergelangan kaki saat beraktivitas atau berolahraga bila disarankan, dan lakukan latihan keseimbangan secara rutin.$e$),
(57,$e$- Gunakan alas kaki yang menopang dan sesuai ukuran, dan hindari berjalan tanpa alas kaki pada permukaan yang keras.$e$),
(58,$e$- Naikkan aktivitas berjalan atau berolahraga secara bertahap.$e$),
(59,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya penguatan band eversi-inversi-dorsofleksi serta single leg stance, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(60,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ankle pump dan alfabet serta ROM aktif pergelangan kaki, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(61,$e$- Lakukan latihan mobilitas tulang belakang dan pernapasan dalam setiap hari, karena rutinitas ini membantu menjaga kelenturan tubuh.$e$),
(62,$e$- Tetap bergerak ringan setiap hari dan lakukan latihan rentang gerak sendi dalam batas yang nyaman.$e$),
(63,$e$- Hangatkan sendi yang kaku sebelum latihan, dan beristirahat secukupnya saat sendi terasa lebih nyeri.$e$),
(64,$e$- Hindari gerakan memutar lutut saat kaki menapak serta jongkok dalam sampai dinyatakan aman oleh terapis atau dokter.$e$),
(65,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya quad set serta ROM lutut, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(66,$e$- Atur ergonomi tempat kerja atau belajar: layar sejajar dengan mata dan punggung bersandar.$e$),
(67,$e$- Berdiri atau bergerak, dan lakukan peregangan ringan setiap 30–60 menit.$e$),
(68,$e$- Hindari membawa tas atau beban pada satu sisi tubuh dalam waktu lama.$e$),
(69,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pelvic tilt berbaring serta peregangan hip flexor, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(70,$e$- Hindari gerakan lengan ke atas dan ke belakang secara ekstrem atau mendadak, dan gunakan penyangga bila disarankan.$e$),
(71,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik rotator cuff serta scapular setting, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(72,$e$- Lakukan peregangan betis dan telapak kaki secara rutin.$e$),
(73,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ankle pump dan alfabet serta isometrik pergelangan kaki, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(74,$e$- Minum obat dan kontrol rutin sesuai anjuran dokter.$e$),
(75,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM sendi dan peregangan ringan serta AROM sendi terkait.$e$),
(76,$e$- Naikkan aktivitas secara bertahap dan hindari mengangkat beban berat sebelum diizinkan.$e$),
(77,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya AROM sendi terkait serta pernapasan diafragma.$e$),
(78,$e$- Tetap gerakkan lutut secara ringan agar tidak kaku, dan jaga berat badan ideal untuk mengurangi beban pada lutut.$e$),
(79,$e$- Kurangi sementara aktivitas jongkok dalam, berlutut, atau naik turun tangga yang berulang apabila nyeri bertambah.$e$),
(80,$e$- Perkuat otot paha dan pinggul secara bertahap.$e$),
(81,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM lutut serta quad set, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(82,$e$- Kurangi sementara aktivitas mengangkat lengan di atas kepala atau membawa beban berat dengan lengan yang nyeri.$e$),
(83,$e$- Hindari tidur terus-menerus menindih bahu yang sakit hingga keluhan berkurang.$e$),
(84,$e$- Gerakkan bahu secara ringan setiap hari dalam batas yang nyaman dan hindari mendiamkan bahu terlalu lama.$e$),
(85,$e$- Kurangi sementara jongkok dalam, berlutut, dan naik turun tangga yang berulang, serta perkuat otot paha dan pinggul secara bertahap.$e$),
(86,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya quad set serta straight leg raise, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(87,$e$- Pilih sepatu dengan ruang jari yang cukup dan hindari sepatu sempit atau berhak tinggi dalam waktu lama.$e$),
(88,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya toe spreading serta peregangan ibu jari kaki, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(89,$e$- Gerakkan sendi di sekitar area luka bakar secara rutin dan jaga posisi sendi agar tidak mengerut.$e$),
(90,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan anti-kontraktur dan positioning serta AROM sendi terkait.$e$),
(91,$e$- Lakukan peregangan telapak kaki dan betis sebelum turun dari tempat tidur pada pagi hari, dan gunakan alas kaki yang menopang lengkung kaki.$e$),
(92,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan fasia plantar serta peregangan betis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(93,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif pergelangan kaki serta isometrik pergelangan kaki, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(94,$e$- Atur posisi layar laptop atau ponsel sejajar dengan mata, dan lakukan peregangan leher ringan setiap 30–60 menit saat bekerja.$e$),
(95,$e$- Gunakan bantal yang menopang leher dalam posisi lurus dan hindari tidur tengkurap.$e$),
(96,$e$- Hindari menunduk atau menahan posisi leher yang sama dalam waktu lama.$e$),
(97,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya chin tuck serta ROM aktif servikal, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(98,$e$- Informasikan kepada terapis apabila keluhan terasa bertambah, atau muncul pusing berputar, kelemahan lengan, maupun kesemutan yang bertambah.$e$),
(99,$e$- Perhatikan postur leher dan bahu saat bekerja, dan lakukan peregangan leher ringan secara teratur.$e$),
(100,$e$- Atur posisi layar dan postur duduk, serta istirahatkan mata dan leher dari layar setiap 30 menit.$e$),
(101,$e$- Jaga pola tidur yang teratur dan cukupi kebutuhan minum.$e$),
(102,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya chin tuck serta peregangan upper trapezius.$e$),
(103,$e$- Apabila muncul nyeri kepala yang sangat hebat dan mendadak, atau disertai kelemahan maupun gangguan penglihatan, sebaiknya segera hubungi dokter.$e$),
(104,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pacing dan graded activity serta pernapasan diafragma.$e$),
(105,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif siku dan lengan bawah serta tendon gliding.$e$),
(106,$e$- Gerakkan area yang nyeri secara lembut dan teratur dalam batas nyaman agar tidak kaku, sesuai arahan terapis.$e$),
(107,$e$- Lakukan aktivitas secara bertahap dan teratur dengan jeda istirahat, daripada menunggu nyeri hilang sepenuhnya.$e$),
(108,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya mirror therapy serta desensitisasi dan re-edukasi sensorik.$e$),
(109,$e$- Berikan stimulasi yang sesuai dengan usia dan perkembangan anak.$e$),
(110,$e$- Ajak anak berpindah posisi dan bermain agar tidak berada pada satu posisi terlalu lama.$e$),
(111,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya AROM sendi terkait serta permainan motorik kasar.$e$),
(112,$e$- Informasikan kepada terapis atau dokter anak apabila terdapat kejang atau kemampuan anak yang sebelumnya sudah dimiliki menurun.$e$),
(113,$e$- Lakukan aktivitas ringan secara teratur dan hindari mendiamkan bagian tubuh yang nyeri terlalu lama.$e$),
(114,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan umum, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(115,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya AROM sendi terkait serta peregangan umum, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(116,$e$- Hindari menekan lengan atas saat tidur atau bersandar, dan gunakan penyangga pergelangan tangan bila disarankan.$e$),
(117,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif pergelangan tangan serta tendon gliding, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(118,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya heel slide serta bridging, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(119,$e$- Perbaiki posisi duduk dengan punggung bersandar, dan lakukan peregangan ringan setiap 30–60 menit.$e$),
(120,$e$- Latihan napas dalam dapat membantu mengendurkan otot di sekitar tulang rusuk dan punggung atas.$e$),
(121,$e$- Hindari membawa beban berat dengan punggung membulat.$e$),
(122,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan ekspansi iga lateral serta ekstensi torakal di dinding, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(123,$e$- Tetap aktif dengan berjalan ringan dalam batas yang nyaman, dan hindari duduk atau berdiri terlalu lama.$e$),
(124,$e$- Hindari duduk bersila atau menyilangkan kaki bila memicu nyeri, dan gunakan bantal di antara kedua lutut saat tidur miring.$e$),
(125,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya heel slide serta quad set, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(126,$e$- Kurangi gerakan menjepit dan memegang dengan ibu jari secara berulang, misalnya saat menggendong anak atau memakai ponsel, dan topang dengan seluruh telapak tangan.$e$),
(127,$e$- Hindari menggenggam atau menjepit dengan kuat dalam waktu lama.$e$),
(128,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan Finkelstein serta oposisi dan abduksi ibu jari, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(129,$e$- Hindari duduk terlalu lama pada permukaan yang keras dan ubah posisi duduk secara berkala.$e$),
(130,$e$- Hindari menekan area yang terasa kesemutan atau baal dalam waktu lama.$e$),
(131,$e$- Kontrol penyakit penyerta, seperti kadar gula darah, sesuai anjuran dokter.$e$),
(132,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan piriformis serta rotasi lumbal berbaring.$e$),
(133,$e$- Tetap aktif dan lanjutkan aktivitas ringan sehari-hari sesuai kemampuan, karena bergerak justru membantu proses pemulihan.$e$),
(134,$e$- Hindari duduk atau berdiri terlalu lama; ubah posisi dan lakukan peregangan ringan setiap 30–60 menit.$e$),
(135,$e$- Saat mengangkat beban, tekuk lutut dan dekatkan beban ke badan, serta hindari membungkuk dan memutar badan secara bersamaan.$e$),
(136,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pelvic tilt berbaring serta knee-to-chest bergantian, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(137,$e$- Informasikan kepada terapis apabila keluhan terasa bertambah, atau muncul kesemutan, kelemahan pada tungkai, maupun gangguan buang air kecil dan besar.$e$),
(138,$e$- Hindari beban yang bertumpu pada pergelangan tangan dan gerakan memutar yang kuat hingga nyeri berkurang.$e$),
(139,$e$- Perbaiki posisi saat mengetik atau memegang ponsel agar pergelangan tangan tetap dalam posisi netral.$e$),
(140,$e$- Istirahatkan tangan secara berkala dari gerakan yang berulang, dan lakukan peregangan ringan pada pergelangan tangan dan jari.$e$),
(141,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ekstensi jari dan finger blocking serta tendon gliding, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(142,$e$- Perkuat otot penopang sendi dengan latihan yang terkontrol.$e$),
(143,$e$- Gerakkan sendi dalam rentang yang nyaman dan hindari peregangan atau gerakan hingga ujung rentang.$e$),
(144,$e$- Gunakan penyangga apabila disarankan saat beraktivitas berat.$e$),
(145,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya stabilisasi isometrik rentang tengah serta retraksi skapula.$e$),
(146,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya weight shifting dan keseimbangan dengan prostesis serta penguatan otot residual dan sendi proksimal.$e$),
(147,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya knee-to-chest bergantian serta rotasi lumbal berbaring.$e$),
(148,$e$- Pilih aktivitas ringan yang disukai, seperti berjalan santai atau berenang, dan tambahkan durasinya secara perlahan.$e$),
(149,$e$- Gunakan alas kaki yang sesuai dan lakukan latihan penguatan otot telapak kaki secara rutin.$e$),
(150,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya short foot dan towel curl serta peregangan betis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(151,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya quad set serta straight leg raise.$e$),
(152,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ankle pump dan alfabet serta quad set.$e$),
(153,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya quad set serta ROM lutut.$e$),
(154,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya tendon gliding serta ekstensi jari dan finger blocking.$e$),
(155,$e$- Gerakkan bahu secara perlahan setiap hari dalam batas nyeri yang masih dapat ditoleransi agar gerakan bahu tidak semakin terbatas.$e$),
(156,$e$- Hindari memaksakan gerakan bahu secara tiba-tiba atau menarik lengan dengan keras.$e$),
(157,$e$- Hindari membawa tas pada satu bahu dalam waktu yang lama, dan usahakan membagi beban secara seimbang.$e$),
(158,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pendulum serta finger walk di dinding.$e$),
(159,$e$- Lakukan latihan postur dan penguatan punggung secara rutin, serta kontrol berkala untuk memantau perkembangan postur.$e$),
(160,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan adduktor serta peregangan piriformis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(161,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya abduksi hip miring serta clamshell, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(162,$e$- Hindari duduk bersila atau menyilangkan kaki bila memicu nyeri, dan hindari tidur menindih sisi yang nyeri.$e$),
(163,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik abduksi hip serta heel slide, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(164,$e$- Kurangi sementara gerakan menggenggam, memutar pergelangan, atau mengangkat benda dengan lengan lurus secara berulang, dan gunakan kedua tangan bila memungkinkan.$e$),
(165,$e$- Perbaiki cara memegang dan mengangkat benda agar beban tidak bertumpu pada siku.$e$),
(166,$e$- Lakukan peregangan lengan bawah secara rutin.$e$),
(167,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik wrist extensor serta peregangan fleksor pergelangan, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(168,$e$- Saat sendi terasa nyeri dan bengkak, istirahatkan sendi tersebut dan kompres dingin selama 10–15 menit; kontrol pola makan dan asam urat sesuai anjuran dokter.$e$),
(169,$e$- Lindungi mata dari debu dan angin serta jaga agar tidak kering, terutama bila mata sulit menutup sempurna.$e$),
(170,$e$- Hindari menarik atau memijat wajah dengan terlalu kuat.$e$),
(171,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya relaksasi wajah dan rahang serta relaksasi progresif / body scan.$e$),
(172,$e$- Apabila muncul kelemahan pada lengan atau tungkai, bicara pelo, atau nyeri kepala hebat, sebaiknya segera hubungi dokter.$e$),
(173,$e$- Libatkan sisi tubuh yang lemah pada aktivitas sehari-hari sesuai arahan terapis, dan ajak keluarga membantu saat berlatih di rumah.$e$),
(174,$e$- Pastikan lingkungan rumah aman, misalnya lantai tidak licin dan tersedia pegangan, serta berjalan dengan pendamping bila masih mudah goyah.$e$),
(175,$e$- Kontrol rutin dan minum obat sesuai anjuran dokter.$e$),
(176,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM pasif dan positioning serta latihan mobilitas di tempat tidur.$e$),
(177,$e$- Apabila muncul kelemahan baru, bicara pelo, atau nyeri kepala hebat yang tidak biasa, sebaiknya segera hubungi dokter.$e$),
(178,$e$- Hindari posisi yang memperberat nyeri pada tungkai, seperti duduk membungkuk terlalu lama, dan cari posisi yang terasa paling nyaman saat beristirahat.$e$),
(179,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya press-up tengkurap serta pelvic tilt berbaring, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(180,$e$- Hindari gerakan menekuk pinggul terlalu dalam yang disertai memutar, seperti jongkok dalam atau duduk bersila.$e$),
(181,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya heel slide serta clamshell, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(182,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan hip flexor serta heel slide, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(183,$e$- Tetap aktif dengan olahraga ringan seperti berjalan atau bersepeda, dan jaga berat badan ideal untuk mengurangi beban pada lutut.$e$),
(184,$e$- Atur ergonomi kerja agar bahu tidak terangkat dan lakukan peregangan leher-bahu setiap 30–60 menit.$e$),
(185,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan levator scapulae serta peregangan upper trapezius, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(186,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya stabilisasi isometrik rentang tengah.$e$),
(187,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan hip flexor serta peregangan hamstring, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(188,$e$- Ikuti anjuran dokter mengenai penggunaan korset serta batasan membungkuk, memutar badan, dan mengangkat beban.$e$),
(189,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya aktivasi transversus abdominis serta ankle pump dan alfabet, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(190,$e$- Ubah posisi secara perlahan, misalnya duduk terlebih dahulu beberapa saat sebelum berdiri dari tempat tidur.$e$),
(191,$e$- Pastikan area rumah aman dan gunakan pegangan apabila terasa pusing.$e$),
(192,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya latihan keseimbangan serta jalan kaki bertahap.$e$),
(193,$e$- Apabila pusing disertai pandangan ganda, bicara pelo, atau kelemahan pada wajah maupun anggota gerak, sebaiknya segera hubungi dokter.$e$),
(194,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan ibu jari kaki serta short foot dan towel curl, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(195,$e$- Hindari posisi atau gerakan yang memicu keluhan, dan ubah posisi secara berkala.$e$),
(196,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan ibu jari kaki serta short foot dan towel curl.$e$),
(197,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya AROM sendi terkait, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(198,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan umum serta relaksasi progresif / body scan, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(199,$e$- Atur frekuensi aktivitas melompat dan berlari, lalu tingkatkan secara bertahap sesuai kemampuan.$e$),
(200,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik quadriceps dengan beban serta quad set, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(201,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan pektoralis di pintu serta ekstensi torakal di dinding, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(202,$e$- Hindari gerakan yang membuka kedua tungkai terlalu lebar, dan gunakan bantal di antara kedua lutut saat tidur miring.$e$),
(203,$e$- Kontraksikan otot dasar panggul terlebih dahulu sebelum batuk, bersin, atau mengangkat beban.$e$),
(204,$e$- Cukupi kebutuhan minum dan serat agar tidak perlu mengejan saat buang air besar.$e$),
(205,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pelvic tilt merangkak serta isometrik adduksi.$e$),
(206,$e$- Informasikan kepada dokter atau terapis apabila terdapat perdarahan yang tidak biasa, demam, atau nyeri yang bertambah.$e$),
(207,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan betis serta peregangan fasia plantar, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(208,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan hamstring serta cat-camel.$e$),
(209,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya latihan postur dinding serta micro-break dan koreksi postur kerja, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(210,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya counter-pressure maneuvers serta bersepeda atau dayung recumbent.$e$),
(211,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya mobilitas di tempat tidur dan transfer serta sit-to-stand.$e$),
(212,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya micro-break dan koreksi postur kerja serta peregangan umum, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(213,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya retraksi skapula serta peregangan pektoralis di pintu, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(214,$e$- Kurangi sementara aktivitas yang memberi hentakan seperti berlari atau melompat, lalu tingkatkan kembali secara bertahap.$e$),
(215,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ankle pump dan alfabet serta aqua exercise / berenang, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(216,$e$- Hindari berdiri bertumpu pada satu kaki dalam waktu lama dan usahakan membagi beban tubuh secara seimbang pada kedua kaki.$e$),
(217,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pelvic tilt berbaring serta aktivasi transversus abdominis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(218,$e$- Lakukan latihan penguatan otot secara teratur dan cukupi asupan protein sesuai anjuran dokter atau ahli gizi.$e$),
(219,$e$- Hindari membawa beban berat pada bahu dan menahan lengan di atas kepala dalam waktu lama.$e$),
(220,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan skalenus serta peregangan pektoralis di pintu.$e$),
(221,$e$- Perhatikan postur bahu agar tidak membungkuk, dan lakukan latihan penguatan penstabil tulang belikat secara bertahap.$e$),
(222,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya scapular setting serta retraksi skapula, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(223,$e$- Hindari gerakan melengkungkan punggung ke belakang secara berulang atau berlebihan, serta olahraga yang membebani punggung bawah sampai dinyatakan aman.$e$),
(224,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif pergelangan kaki serta peregangan betis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(225,$e$- Istirahatkan lengan secara bergantian dari gerakan yang memicu keluhan, dan gunakan kedua tangan saat mengangkat benda.$e$),
(226,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan suboksipital serta chin tuck, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(227,$e$- Gunakan bantal duduk berbentuk donat saat duduk lama dan hindari duduk pada permukaan yang keras.$e$),
(228,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya rotasi lumbal berbaring serta peregangan piriformis, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(229,$e$- Pilih makanan yang lebih lunak untuk sementara waktu dan hindari mengunyah makanan keras atau permen karet.$e$),
(230,$e$- Hindari membuka mulut terlalu lebar dan kebiasaan menggertakkan gigi.$e$),
(231,$e$- Perbaiki postur kepala dan leher serta lakukan latihan rahang yang telah diajarkan.$e$),
(232,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya relaksasi wajah dan rahang serta latihan rahang terkontrol, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(233,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya isometrik wrist extensor serta peregangan ekstensor pergelangan, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(234,$e$- Ajak anak berjalan dengan menapakkan tumit melalui permainan, dan lakukan peregangan betis secara lembut.$e$),
(235,$e$- Gerakkan leher dengan lembut dalam batas yang nyaman dan hindari menarik atau memaksa leher.$e$),
(236,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif servikal serta peregangan sternocleidomastoid, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(237,$e$- Hindari menggenggam kuat atau memegang benda dalam waktu lama, dan gerakkan jari secara perlahan setiap hari.$e$),
(238,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya tendon gliding serta ekstensi jari dengan karet, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(239,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan pektoralis di pintu serta chin tuck, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(240,$e$- Gerakkan leher secara perlahan dalam batas yang nyaman, dan hindari gerakan menyentak atau menahan leher pada satu posisi terlalu lama.$e$),
(241,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM aktif servikal serta chin tuck.$e$),
(242,$e$- Gunakan sisi tubuh yang lemah dalam aktivitas sehari-hari sesuai arahan terapis, dan hindari berada pada satu posisi yang sama terlalu lama.$e$),
(243,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya reach duduk serta weight shifting.$e$),
(244,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM pasif dan positioning serta pendulum.$e$),
(245,$e$- Kompres hangat ringan pada wajah dapat membantu, dan lakukan gerakan wajah yang lembut tanpa memaksa.$e$),
(246,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya latihan otot wajah di depan cermin serta relaksasi wajah dan rahang.$e$),
(247,$e$- Hindari posisi pergelangan tangan tertekuk atau terangkat terlalu lama saat mengetik, memakai ponsel, atau tidur; usahakan pergelangan tetap pada posisi netral.$e$),
(248,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya median nerve glide serta ROM aktif pergelangan tangan.$e$),
(249,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya rotasi lumbal berbaring serta pelvic tilt berbaring.$e$),
(250,$e$- Periksa kaki setiap hari dan gunakan alas kaki yang nyaman untuk melindungi kaki yang terasa baal.$e$),
(251,$e$- Hindari menekuk siku terlalu lama, misalnya saat menelepon, dan hindari bertumpu pada siku.$e$),
(252,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ulnar nerve glide serta ROM aktif siku dan lengan bawah.$e$),
(253,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya desensitisasi dan re-edukasi sensorik serta latihan keseimbangan statis-dinamis.$e$),
(254,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya Brandt-Daroff serta gaze stabilization.$e$),
(255,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM pasif dan positioning serta penguatan band eversi-inversi-dorsofleksi.$e$),
(256,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan adduktor serta heel slide.$e$),
(257,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya tummy time serta stimulasi gerak.$e$),
(258,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan ekspansi iga lateral serta rotasi torakal.$e$),
(259,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya gaze stabilization serta latihan keseimbangan.$e$),
(260,$e$- Atur aktivitas dengan jeda istirahat yang cukup dan hindari berada di tempat yang terlalu panas.$e$),
(261,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan spastisitas serta peregangan umum.$e$),
(262,$e$- Lakukan gerakan dengan ukuran besar dan irama yang jelas, serta berlatih pada saat obat bekerja optimal.$e$),
(263,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya latihan amplitudo besar serta peregangan spastisitas.$e$),
(264,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya relaksasi dasar panggul serta pernapasan 360 derajat.$e$),
(265,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya radial nerve glide serta ROM aktif pergelangan tangan.$e$),
(266,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya neural slider ischiadikus serta pelvic tilt berbaring.$e$),
(267,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya peregangan spastisitas serta ROM pasif dan positioning.$e$),
(268,$e$- Atur jarak berjalan dengan jeda istirahat; posisi sedikit membungkuk saat berjalan umumnya terasa lebih nyaman.$e$),
(269,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya knee-to-chest bergantian serta child's pose, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(270,$e$- Lakukan latihan otot dasar panggul secara teratur setiap hari, dan hindari mengangkat beban berat tanpa mengaktifkan otot dasar panggul.$e$),
(271,$e$- Hindari gerakan sit-up atau crunch pada tahap awal, dan fokus pada latihan pernapasan serta penguatan otot perut bagian dalam.$e$),
(272,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya pernapasan 360 derajat serta ko-aktivasi TrA dan dasar panggul.$e$),
(273,$e$- Gerakkan bahu secara bertahap setiap hari sesuai arahan terapis, dan perhatikan bila lengan terasa membengkak atau berat.$e$),
(274,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya ROM bahu progresif pasca mastektomi serta pernapasan ekspansi iga lateral.$e$),
(275,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya aktivasi transversus abdominis serta ankle pump dan alfabet.$e$),
(276,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya jalan kaki bertahap serta peregangan umum.$e$),
(277,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya jalan kaki bertahap serta peregangan umum, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$),
(278,$e$- Kurangi sementara jarak lari dan hindari berlari pada permukaan yang miring.$e$),
(279,$e$- Lakukan latihan di rumah secara rutin sesuai arahan terapis, misalnya clamshell serta abduksi hip miring, kemudian dilanjutkan dengan latihan penguatan secara bertahap setelah keluhan membaik.$e$)
), t(name,ids) as (values
($n$Bronchiectasis$n$,array[0,1,2,3]),
($n$Bronchitis$n$,array[0,1,2,3]),
($n$Broncho Pneumonia$n$,array[0,1,2,3]),
($n$Bronchospasm$n$,array[4,5,6,3]),
($n$Chronic obstructive pulmonary disease$n$,array[7,8,6,3]),
($n$Pneumonia$n$,array[0,1,2,3]),
($n$Post-COVID condition$n$,array[9,10,6,11,3]),
($n$Pulmonary fibrosis$n$,array[12,13,6,3]),
($n$Respiratory failure$n$,array[14,6,2,3]),
($n$Chronic pain syndrome$n$,array[15,16,17,18,19]),
($n$Frailty$n$,array[20,21,22,19]),
($n$Kelemahan Umum$n$,array[23,21,22,24,19]),
($n$Malaise dan Fatigue$n$,array[23,21,22,24,19]),
($n$Osteoporosis dengan Fraktur$n$,array[25,21,22,26,19]),
($n$Penurunan Keseimbangan$n$,array[20,21,22,19]),
($n$Polyosteoarthritis$n$,array[27,28,29,30,31,19]),
($n$Reduced Mobility$n$,array[32,21,22,24,19]),
($n$Repeated Falls$n$,array[20,21,22,19]),
($n$Risiko Jatuh$n$,array[20,21,22,19]),
($n$Senility$n$,array[20,21,22,19]),
($n$Konsultasi$n$,array[33,34,35,36,19]),
($n$Abdominal Pain$n$,array[37,38,39,40]),
($n$Achilles tendon rupture$n$,array[41,42,43,44,45]),
($n$Acquired absence of arm below elbow$n$,array[46,42,43,47,45]),
($n$Acquired absence of both legs$n$,array[46,42,43,47,45]),
($n$Acquired absence of leg below knee$n$,array[46,42,43,47,45]),
($n$Acromioclavicular Sprain$n$,array[48,49,50,51,52,19]),
($n$Adductor strain$n$,array[53,49,54,55,52,19]),
($n$Ankle instability, chronic$n$,array[56,57,58,59,31,19]),
($n$Ankle sprain$n$,array[56,49,54,60,52,19]),
($n$Ankylosing spondylitis$n$,array[61,62,63,19]),
($n$Anterior Lateral Ligament$n$,array[64,49,54,65,52,19]),
($n$Anterior pelvic tilt$n$,array[66,67,68,69,31,19]),
($n$Anterior shoulder dislocation$n$,array[70,49,54,71,52,19]),
($n$Anterior tibialis tendinitis$n$,array[57,58,72,73,31,19]),
($n$Autoimun$n$,array[62,63,74,75,19]),
($n$Avulsion Fracture$n$,array[42,43,76,77,45]),
($n$Baker's cyst$n$,array[78,79,80,81,31,19]),
($n$Biceps Strain$n$,array[49,54,50,51,52,19]),
($n$Bicipital instability$n$,array[82,83,84,51,31,19]),
($n$Bicipital tendinitis$n$,array[82,83,84,51,31,19]),
($n$Bipartite patella$n$,array[85,78,86,31,19]),
($n$Bunion$n$,array[87,57,58,88,31,19]),
($n$Burn of lower limb$n$,array[89,42,43,90,45]),
($n$Burn of trunk$n$,array[89,42,43,90,45]),
($n$Burn of upper limb$n$,array[89,42,43,90,45]),
($n$Calcaneal apophysitis (Sever's disease)$n$,array[91,58,92,31,19]),
($n$Calcaneus spur$n$,array[91,58,92,31,19]),
($n$Calcific tendinitis of shoulder$n$,array[82,83,84,51,31,19]),
($n$Calf muscle tightness$n$,array[41,57,58,93,31,19]),
($n$Cervical disc displacement$n$,array[94,95,96,97,31,98]),
($n$Cervicalgia$n$,array[94,95,96,97,31,98]),
($n$Cervicogenic headache$n$,array[99,100,101,102,103]),
($n$Chondromalacia patella$n$,array[85,78,86,31,19]),
($n$Chronic fatigue syndrome$n$,array[23,16,17,104,19]),
($n$Clavicle malunion$n$,array[42,43,76,105,45]),
($n$Complex regional pain syndrome I$n$,array[106,107,16,108,19]),
($n$Congenital musculoskeletal deformities$n$,array[109,110,111,112]),
($n$Contracture of muscle$n$,array[113,28,29,114,31,19]),
($n$contusion$n$,array[49,54,50,115,52,19]),
($n$Contusion adductor$n$,array[53,49,54,55,52,19]),
($n$Contusion brachioradialis$n$,array[116,49,54,117,52,19]),
($n$Contusion Hamstring$n$,array[53,49,54,118,52,19]),
($n$contusion pectoralis$n$,array[49,54,50,51,52,19]),
($n$Costovertebral joint dysfunction$n$,array[119,120,121,122,31,19]),
($n$Coxytis$n$,array[123,124,28,125,31,19]),
($n$De Quervain disease$n$,array[126,127,128,31,19]),
($n$Deep gluteal syndrome$n$,array[129,130,131,132,19]),
($n$Degenerative disc disease cervical$n$,array[94,95,96,97,31,98]),
($n$Degenerative disc disease lumbar$n$,array[133,134,135,136,31,137]),
($n$Dorsal Wrist impingement$n$,array[138,139,127,117,31,19]),
($n$Dupuytren's contracture$n$,array[140,139,127,141,31,19]),
($n$Ehlers-Danlos syndrome$n$,array[142,143,144,145,19]),
($n$Encounter for orthopedic aftercare$n$,array[42,43,76,77,45]),
($n$Encounter for training in use of prosthetic device$n$,array[46,42,43,146,45]),
($n$Facet joint syndrome$n$,array[133,134,135,147,31,137]),
($n$Fibromyalgia$n$,array[148,107,16,18,19]),
($n$First rib dysfunction$n$,array[119,120,121,122,31,19]),
($n$Flat Foot$n$,array[149,58,72,150,31,19]),
($n$Fracture$n$,array[42,43,76,77,45]),
($n$Fracture metatarsal$n$,array[42,43,76,151,45]),
($n$Fracture of neck of femur$n$,array[42,43,76,152,45]),
($n$Fracture patella$n$,array[42,43,76,153,45]),
($n$Fraktur Ulna$n$,array[42,43,76,154,45]),
($n$Frozen shoulder$n$,array[155,156,157,158,31,19]),
($n$Functional kyphosis$n$,array[159,66,67,31,19]),
($n$Functional leg length discrepancy$n$,array[66,67,68,160,31,19]),
($n$Functional lordosis$n$,array[66,67,68,69,31,19]),
($n$Functional scoliosis$n$,array[159,66,67,31,19]),
($n$Genu valgum$n$,array[78,79,80,161,31,19]),
($n$Genu varum$n$,array[78,79,80,161,31,19]),
($n$Gluteal tendinopathy$n$,array[162,123,28,163,31,19]),
($n$Golfer's elbow$n$,array[164,165,166,167,31,19]),
($n$Gout Arthritis$n$,array[168,62,63,75,19]),
($n$Greater trochanteric pain syndrome$n$,array[162,123,28,163,31,19]),
($n$Groin Strain$n$,array[53,49,54,55,52,19]),
($n$Hallux Valgus$n$,array[87,57,58,88,31,19]),
($n$Hamstring strain$n$,array[53,49,54,118,52,19]),
($n$Hamstring Tightness$n$,array[53,123,124,118,31,19]),
($n$Hemifacial spasm$n$,array[169,170,171,172]),
($n$Hemiplegia unspecified$n$,array[173,174,175,176,177]),
($n$Hernia Nucleus Pulposus$n$,array[178,133,135,179,31,137]),
($n$Hip impingement syndrome$n$,array[180,123,124,181,31,19]),
($n$Hip pain$n$,array[123,124,28,125,31,19]),
($n$History of fall$n$,array[20,21,22,19]),
($n$Hypermobility spectrum disorder$n$,array[142,143,144,145,19]),
($n$Iliopsoas tendinitis$n$,array[123,124,28,182,31,19]),
($n$Ischiofemoral impingement$n$,array[180,123,124,181,31,19]),
($n$Juvenile arthritis$n$,array[62,63,74,75,19]),
($n$Knee instability$n$,array[64,78,79,65,31,19]),
($n$Knee osteoarthritis$n$,array[183,79,80,65,31,19]),
($n$Knee Pain$n$,array[78,79,80,65,31,19]),
($n$Kyphosis$n$,array[159,66,67,31,19]),
($n$Labral tear of hip$n$,array[180,49,54,181,52,19]),
($n$Late effect of burn$n$,array[89,42,43,90,45]),
($n$Lateral pelvic tilt$n$,array[66,67,68,160,31,19]),
($n$Levator scapulae syndrome$n$,array[184,84,157,185,31,19]),
($n$Ligament sprain (general)$n$,array[49,54,50,115,52,19]),
($n$Ligamentous laxity$n$,array[113,28,29,186,31,19]),
($n$Lordosis$n$,array[66,67,68,69,31,19]),
($n$Low back pain$n$,array[133,134,135,136,31,137]),
($n$Lower cross syndrome$n$,array[66,67,68,187,31,19]),
($n$Lumbar fracture$n$,array[188,133,134,189,137]),
($n$Lumbar spondylosis$n$,array[133,134,135,147,31,137]),
($n$Lumbosacral strain$n$,array[133,134,135,136,31,137]),
($n$Malunion of fracture$n$,array[42,43,76,77,45]),
($n$Mechanical thoracic pain$n$,array[119,120,121,122,31,19]),
($n$Medial plica syndrome$n$,array[85,78,86,31,19]),
($n$Meniere's disease$n$,array[190,191,192,193]),
($n$Metatarsalgia$n$,array[87,57,58,194,31,19]),
($n$Morton's neuroma$n$,array[87,195,130,196,19]),
($n$Muscle imbalance$n$,array[20,66,67,31,19]),
($n$muscle tightness$n$,array[113,28,29,114,31,19]),
($n$Muscle weakness$n$,array[113,28,29,197,31,19]),
($n$Myalgia$n$,array[113,28,29,198,31,19]),
($n$Myofascial pain syndrome$n$,array[113,28,29,198,31,19]),
($n$Nonunion of fracture$n$,array[42,43,76,77,45]),
($n$Osgood-Schlatter disease$n$,array[199,78,79,200,31,19]),
($n$Osteitis pubis$n$,array[53,123,124,55,31,19]),
($n$Osteoarthritis of hip$n$,array[162,123,28,125,31,19]),
($n$Pain in foot$n$,array[57,58,72,60,31,19]),
($n$Patella alta/baja$n$,array[85,78,86,31,19]),
($n$Patellar instability$n$,array[85,78,86,31,19]),
($n$Pathological fracture$n$,array[42,43,76,77,45]),
($n$Pectoralis Strain$n$,array[49,54,50,51,52,19]),
($n$Pectus Excavatum$n$,array[113,28,29,201,31,19]),
($n$Pelvic girdle pain$n$,array[202,203,204,205,206]),
($n$Peroneal tendinitis$n$,array[57,58,72,73,31,19]),
($n$pes anserinus bursitis$n$,array[78,79,80,86,31,19]),
($n$Pes cavus$n$,array[149,58,72,207,31,19]),
($n$Piriformis Syndrome$n$,array[129,130,131,132,19]),
($n$Plantar fasciitis$n$,array[91,58,92,31,19]),
($n$Plantar plate injury$n$,array[87,49,54,194,52,19]),
($n$Post-traumatic osteoarthritis$n$,array[27,28,29,30,31,19]),
($n$Posterior pelvic tilt$n$,array[66,67,68,208,31,19]),
($n$Posterior shoulder dislocation$n$,array[70,49,54,71,52,19]),
($n$Posterior shoulder instability$n$,array[70,84,157,71,31,19]),
($n$Posterior tibial tendon dysfunction$n$,array[57,58,72,73,31,19]),
($n$Postural abnormality$n$,array[66,67,68,209,31,19]),
($n$Postural kyphosis$n$,array[159,66,67,31,19]),
($n$Postural orthostatic tachycardia syndrome (POTS)$n$,array[190,191,210,193]),
($n$Postural strain$n$,array[66,67,68,209,31,19]),
($n$Psoriatic arthritis$n$,array[62,63,74,75,19]),
($n$Pubic symphysis dysfunction$n$,array[202,203,204,205,206]),
($n$Quadriceps muscle tightness$n$,array[53,123,124,65,31,19]),
($n$Quadriceps strain$n$,array[53,49,54,65,52,19]),
($n$Reactive arthritis$n$,array[62,63,74,75,19]),
($n$Rehabilitation for activities of daily living$n$,array[33,34,35,211,19]),
($n$Repetitive strain injury$n$,array[113,28,29,212,31,19]),
($n$Rheumatoid arthritis$n$,array[62,63,74,75,19]),
($n$rhomboid strain$n$,array[119,120,121,213,31,19]),
($n$Rotator cuff syndrome$n$,array[82,83,84,51,31,19]),
($n$Sacral stress fracture$n$,array[214,133,134,215,137]),
($n$Sacroiliac joint sprain$n$,array[216,133,134,217,31,137]),
($n$Sarcopenia$n$,array[218,21,22,19]),
($n$Scalenus syndrome$n$,array[219,195,130,220,19]),
($n$Scapular dyskinesis$n$,array[221,84,157,222,31,19]),
($n$Scapular winging$n$,array[221,84,157,222,31,19]),
($n$Scheuermann's disease$n$,array[159,66,67,31,19]),
($n$Scoliosis$n$,array[159,66,67,31,19]),
($n$Sesamoiditis$n$,array[87,57,58,194,31,19]),
($n$Shoulder girdle weakness$n$,array[221,84,157,222,31,19]),
($n$Shoulder Impingement$n$,array[82,83,84,51,31,19]),
($n$Shoulder instability$n$,array[70,84,157,71,31,19]),
($n$shoulder pain$n$,array[82,83,84,51,31,19]),
($n$Shoulder subluxation$n$,array[70,49,54,71,52,19]),
($n$SI joint dysfunction$n$,array[216,133,134,217,31,137]),
($n$Sinding-Larsen-Johansson syndrome$n$,array[199,78,79,200,31,19]),
($n$Sinus tarsi syndrome$n$,array[57,58,72,73,31,19]),
($n$SLAP Tear Shoulder$n$,array[70,49,54,71,52,19]),
($n$Snapping hip syndrome$n$,array[123,124,28,182,31,19]),
($n$Snapping scapula syndrome$n$,array[221,84,157,222,31,19]),
($n$Spondyloarthrosis$n$,array[133,134,135,147,31,137]),
($n$Spondylolisthesis$n$,array[223,133,134,217,31,137]),
($n$Spondylolysis$n$,array[223,133,134,217,31,137]),
($n$Sprain Finger$n$,array[49,54,50,117,52,19]),
($n$Sprain Ligament Genu Dextra PFPS$n$,array[49,54,50,161,52,19]),
($n$Sprain of foot$n$,array[56,49,54,60,52,19]),
($n$Sprain Toe$n$,array[49,54,50,194,52,19]),
($n$Stiffness Ankle$n$,array[57,58,72,224,31,19]),
($n$stiffness elbow$n$,array[225,165,166,117,31,19]),
($n$Stiffness Lumbal$n$,array[133,134,135,136,31,137]),
($n$Strain$n$,array[49,54,50,115,52,19]),
($n$Strain Achilles$n$,array[41,49,54,93,52,19]),
($n$Strain Brachioradialis$n$,array[116,49,54,117,52,19]),
($n$Strain Deltoid$n$,array[49,54,50,51,52,19]),
($n$Strain Digiti Minimi$n$,array[49,54,50,117,52,19]),
($n$strain flexor pollicis longus$n$,array[49,54,50,117,52,19]),
($n$Strain Latissimus Dorsi$n$,array[49,54,50,51,52,19]),
($n$Strain Serratus Anterior$n$,array[49,54,50,51,52,19]),
($n$Strain Sternocleidomastoideus$n$,array[94,95,96,226,31,98]),
($n$Strain tendon digitorum$n$,array[49,54,50,117,52,19]),
($n$Strain Teres Major$n$,array[49,54,50,51,52,19]),
($n$Strain Teres Minor$n$,array[49,54,50,51,52,19]),
($n$Subacromial bursitis$n$,array[82,83,84,51,31,19]),
($n$Suboccipital strain$n$,array[94,95,96,226,31,98]),
($n$Tailbone pain$n$,array[227,133,134,228,31,137]),
($n$Temporomandibular joint disorder$n$,array[229,230,231,232,31,19]),
($n$Tendinitis Supraspinatus$n$,array[82,83,84,51,31,19]),
($n$Tendinitis Triceps$n$,array[113,28,29,117,31,19]),
($n$Tendinitis, foot and ankle$n$,array[57,58,72,73,31,19]),
($n$Tennis elbow$n$,array[164,165,166,233,31,19]),
($n$Tension-type headache$n$,array[99,100,101,102,103]),
($n$TFCC injury$n$,array[138,49,54,117,52,19]),
($n$Thoracic hypomobility$n$,array[119,120,121,122,31,19]),
($n$Thoracic spondylosis$n$,array[119,120,121,147,31,19]),
($n$Thoracolumbar junction syndrome$n$,array[133,134,135,122,31,137]),
($n$Thumb Tendonitis$n$,array[126,127,128,31,19]),
($n$Toe walking$n$,array[234,109,110,112]),
($n$Torticollis$n$,array[235,94,95,236,31,98]),
($n$Trapezius strain$n$,array[184,49,54,185,52,19]),
($n$Trigger finger$n$,array[237,140,139,238,31,19]),
($n$Tumor Tulang$n$,array[42,43,76,77,45]),
($n$Turf toe$n$,array[87,49,54,194,52,19]),
($n$Upper cervical dysfunction$n$,array[94,95,96,226,31,98]),
($n$Upper cross syndrome$n$,array[66,67,68,239,31,19]),
($n$Vertebrogenic low back pain$n$,array[133,134,135,136,31,137]),
($n$Whiplash injury$n$,array[240,94,95,241,31,98]),
($n$wrist pain$n$,array[138,139,127,117,31,19]),
($n$wrist sprain$n$,array[138,49,54,117,52,19]),
($n$Wrist Strain$n$,array[138,49,54,117,52,19]),
($n$Ataxia$n$,array[242,174,175,243,177]),
($n$Axillary nerve lesion$n$,array[195,130,131,244,19]),
($n$Bell's palsy$n$,array[245,169,170,246,172]),
($n$Brachial plexus injury$n$,array[195,130,131,244,19]),
($n$Carpal tunnel syndrome$n$,array[247,195,130,248,19]),
($n$Cervical radiculopathy$n$,array[94,95,96,97,31,98]),
($n$Cervical Spondylosis$n$,array[94,95,96,97,31,98]),
($n$Cluneal nerve entrapment$n$,array[195,130,131,249,19]),
($n$Critical illness polyneuropathy$n$,array[250,195,130,176,19]),
($n$CRPS II$n$,array[106,107,16,108,19]),
($n$Cubital tunnel syndrome$n$,array[251,195,130,252,19]),
($n$Diabetic Neuropathy$n$,array[250,195,130,253,19]),
($n$Dizziness and giddiness$n$,array[190,191,254,193]),
($n$Encounter for balance training$n$,array[20,21,22,19]),
($n$Encounter for gait training$n$,array[20,21,22,19]),
($n$Facial asymmetry$n$,array[169,170,246,172]),
($n$Foot drop (peroneal nerve palsy)$n$,array[195,130,131,255,19]),
($n$Functional quadriplegia$n$,array[242,174,175,176,177]),
($n$Gait abnormality$n$,array[20,21,22,19]),
($n$Genitofemoral neuralgia$n$,array[195,130,131,256,19]),
($n$Hypotonia$n$,array[109,110,257,112]),
($n$Intercostal neuralgia$n$,array[195,130,131,258,19]),
($n$Ischialgia$n$,array[178,133,135,179,31,137]),
($n$Labyrinthitis$n$,array[190,191,259,193]),
($n$Long thoracic nerve palsy$n$,array[195,130,131,244,19]),
($n$Lumbal Disc Bulging$n$,array[178,133,135,179,31,137]),
($n$Multiple sclerosis$n$,array[260,174,175,261,177]),
($n$Nerve root compression$n$,array[178,133,135,179,31,137]),
($n$Obturator nerve entrapment$n$,array[195,130,131,256,19]),
($n$Paraparesis Leg$n$,array[242,174,175,176,177]),
($n$Paraplegia$n$,array[242,174,175,176,177]),
($n$Parkinson's disease$n$,array[262,242,174,263,177]),
($n$Peripheral neuropathy$n$,array[250,195,130,253,19]),
($n$Pudendal neuralgia$n$,array[195,130,131,264,19]),
($n$Quadriplegia$n$,array[242,174,175,176,177]),
($n$Radial nerve lesion$n$,array[116,195,130,265,19]),
($n$Radial tunnel syndrome$n$,array[116,195,130,265,19]),
($n$Sciatic neuropathy$n$,array[195,130,131,266,19]),
($n$Spasticity$n$,array[242,174,175,267,177]),
($n$Spinal stenosis cervical region$n$,array[94,95,96,97,31,98]),
($n$Spinal stenosis lumbar region$n$,array[268,133,134,269,31,137]),
($n$Stress incontinence$n$,array[270,204,206]),
($n$Stroke with hemiparesis$n$,array[173,174,175,176,177]),
($n$Suprascapular nerve entrapment$n$,array[221,195,130,244,19]),
($n$Thoracic outlet syndrome$n$,array[219,195,130,220,19]),
($n$Trigeminal neuralgia$n$,array[169,170,171,172]),
($n$Ulnar nerve lesion$n$,array[251,195,130,252,19]),
($n$Urinary incontinence$n$,array[270,204,206]),
($n$Vertigo$n$,array[190,191,254,193]),
($n$Vestibular dysfunction, unspecified$n$,array[190,191,254,193]),
($n$Vestibular neuritis$n$,array[190,191,259,193]),
($n$Diastasis recti$n$,array[271,203,204,272,206]),
($n$Pelvic organ prolapse$n$,array[270,204,206]),
($n$Postpartum muscle strain$n$,array[203,204,272,206]),
($n$Craniotomy$n$,array[173,174,175,176,177]),
($n$Fracture Wrist$n$,array[138,42,43,154,45]),
($n$Malignant neoplasm of breast$n$,array[273,42,43,274,45]),
($n$Post Amputation$n$,array[46,42,43,47,45]),
($n$Post Arthroscopy$n$,array[42,43,76,153,45]),
($n$Post joint replacement (hip)$n$,array[42,43,76,152,45]),
($n$Post joint replacement (knee)$n$,array[42,43,76,152,45]),
($n$Post op ACL and meniscus$n$,array[64,42,43,153,45]),
($n$Post op ACL reconstruction$n$,array[64,42,43,153,45]),
($n$Post op ATFL repair$n$,array[56,42,43,44,45]),
($n$Post op debridement$n$,array[42,43,76,77,45]),
($n$Post op fracture$n$,array[42,43,76,77,45]),
($n$Post Op Fracture Femur$n$,array[42,43,76,152,45]),
($n$Post Op Fracture Humerus$n$,array[42,43,76,105,45]),
($n$Post op lumbar$n$,array[42,43,76,275,45]),
($n$Post op meniscus repair$n$,array[64,42,43,153,45]),
($n$Post Op Tendon Repair$n$,array[42,43,76,154,45]),
($n$Recovery Treatment$n$,array[33,34,35,276,19]),
($n$Achilles tendinitis$n$,array[41,57,58,93,31,19]),
($n$ACL injury$n$,array[64,49,54,65,52,19]),
($n$Ankle Dislocation$n$,array[70,49,54,60,52,19]),
($n$Cuboid Syndrome$n$,array[57,58,72,73,31,19]),
($n$DOMS$n$,array[113,28,29,277,31,19]),
($n$Iliotibial band syndrome$n$,array[278,78,79,279,31,19]),
($n$Jumper's knee$n$,array[199,78,79,200,31,19]),
($n$MCL/LCL sprain$n$,array[64,49,54,65,52,19]),
($n$Meniscus lesion$n$,array[64,49,54,65,52,19]),
($n$Patellar tendinitis$n$,array[199,78,79,200,31,19]),
($n$Patellofemoral pain syndrome$n$,array[85,78,86,31,19]),
($n$PCL injury$n$,array[64,49,54,65,52,19]),
($n$Shin splint$n$,array[57,58,72,73,31,19]),
($n$Sprain Thumb$n$,array[49,54,50,117,52,19]),
($n$Strain Gastroc$n$,array[41,49,54,93,52,19]),
($n$Strain Popliteal$n$,array[49,54,50,81,52,19])
), b as (
  select lower(btrim(t.name)) k, string_agg(s.txt, E'\n' order by x.ord) body
  from t, unnest(t.ids) with ordinality x(id,ord) join s on s.id=x.id group by 1
)
update public.diagnosis_education e
   set advice = b.body
  from b
 where e.diagnosis_key = b.k
   and e.advice is distinct from b.body;
