-- Template Subjective HNP dengan dua varian (dipilih terapis di Isi Subjective Cepat):
--   1. Menjalar (radikuler): nyeri pinggang menjalar ke bokong/paha/betis/kaki.
--   2. Tidak menjalar: nyeri pinggang saja, HNP diketahui dari hasil pencitraan.
-- Varian dipisah baris penanda "@@VARIAN: Nama" (lihat splitVariants di src/lib/subjectiveTemplate.js).
update public.operational_options
   set subjective_template = $fn$@@VARIAN: Menjalar
Pasien datang dengan keluhan nyeri pinggang menjalar ke (bokong/paha/betis/kaki) sisi (kanan/kiri) yang dirasakan sejak (.....) hari/minggu/bulan yang lalu. Keluhan timbul secara (mendadak/bertahap), dipicu oleh (.....), dan sejak itu (membaik/menetap/memburuk/naik turun). Nyeri terutama dirasakan bertambah ketika (duduk lama/membungkuk/batuk/bersin/mengangkat beban/menegakkan badan/duduk/berdiri/berjalan) (.....), dengan kekakuan pada pagi hari selama sekitar (.....) menit. Nyeri terasa (tajam/tumpul/terbakar/berdenyut/seperti tersetrum). Keluhan berkurang saat (.....) dan terutama terasa pada (pagi/siang/malam) hari. Dari hasil (MRI/CT scan/rontgen) tanggal (.....) ditemukan HNP setinggi (L3-L4/L4-L5/L5-S1) (.....).

(Terdapat/Tidak terdapat) keluhan kesemutan, baal, atau kelemahan pada tungkai, serta gangguan buang air kecil maupun buang air besar. (Terdapat/Tidak terdapat) demam, penurunan berat badan tanpa sebab, atau nyeri hebat pada malam hari. Dalam aktivitas sehari-hari, pasien bekerja sebagai (.....) dengan posisi (duduk statis/berdiri lama/sering mengangkat beban) selama (.....) jam per hari, serta memiliki kebiasaan (.....). Pasien (pernah/belum pernah) mengalami keluhan serupa dan (memiliki/tidak memiliki) riwayat cedera, operasi, atau penyakit penyerta berupa (.....). Pengobatan atau terapi sebelumnya berupa (.....) dengan hasil (membaik/tidak membaik). Keluhan ini menyebabkan kesulitan dalam (.....), dan pasien berharap (.....).
@@VARIAN: Tidak menjalar
Pasien datang dengan keluhan nyeri pinggang (setempat/di sisi kanan/di sisi kiri) tanpa nyeri menjalar ke bokong, paha, betis, maupun kaki, yang dirasakan sejak (.....) hari/minggu/bulan yang lalu. Keluhan timbul secara (mendadak/bertahap), dipicu oleh (.....), dan sejak itu (membaik/menetap/memburuk/naik turun). Nyeri terutama dirasakan bertambah ketika (duduk lama/membungkuk/batuk/bersin/mengangkat beban/menegakkan badan/duduk/berdiri/berjalan) (.....), dengan kekakuan pada pagi hari selama sekitar (.....) menit. Nyeri terasa (tajam/tumpul/pegal/berdenyut) dan (hanya di pinggang/disertai rasa tegang pada otot sekitar pinggang). Keluhan berkurang saat (.....) dan terutama terasa pada (pagi/siang/malam) hari. Dari hasil (MRI/CT scan) tanggal (.....) ditemukan HNP setinggi (L3-L4/L4-L5/L5-S1) (.....) (dengan/tanpa) penekanan pada akar saraf, meskipun saat ini pasien tidak mengeluhkan nyeri menjalar.

Tidak ada keluhan kesemutan, baal, atau kelemahan pada tungkai, serta tidak ada gangguan buang air kecil maupun buang air besar. (Terdapat/Tidak terdapat) demam, penurunan berat badan tanpa sebab, atau nyeri hebat pada malam hari. Dalam aktivitas sehari-hari, pasien bekerja sebagai (.....) dengan posisi (duduk statis/berdiri lama/sering mengangkat beban) selama (.....) jam per hari, serta memiliki kebiasaan (.....). Pasien (pernah/belum pernah) mengalami keluhan serupa, termasuk nyeri menjalar sebelumnya, dan (memiliki/tidak memiliki) riwayat cedera, operasi, atau penyakit penyerta berupa (.....). Pengobatan atau terapi sebelumnya berupa (.....) dengan hasil (membaik/tidak membaik). Keluhan ini menyebabkan kesulitan dalam (.....), dan pasien berharap (.....).$fn$
 where category = 'diagnosa'
   and lower(btrim(label)) = 'hernia nucleus pulposus';
